version: '3.7'

networks:
  etoro:
    external: true

services:
  etoro-api:
    build: .
    container_name: etoro_api
    environment:
      LOGIN: ${LOGIN}
      PASSWORD: ${PASSWORD}
    networks:
      - etoro
